version: '3.8'

services:
  db:
    container_name: db
    image: iwannadocontainerstuff/kinoservice_db:latest
    ports:
      - 3306:3306
  app:
    container_name: app
    image: iwannadocontainerstuff/kinoservice_app:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    stdin_open: true
    tty: true 