/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package v2_uebermde;



class AppTest {
    //   App classUnderTest = new App();
    //    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    //}
}//
