name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        # Username used to log against the Docker registry
        username: iwannadocontainerstuff
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DockerHubPW }}

    - name: Build and push kinoservice_app
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:KinoServiceApp"
        push: true
        tags: iwannadocontainerstuff/kinoservice_app:${{ github.run_number }}.${{ github.run_attempt }},iwannadocontainerstuff/kinoservice_app:latest

    - name: Build and push db
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:KinoServiceDB"
        push: true
        tags: iwannadocontainerstuff/kinoservice_db:${{ github.run_number }}.${{ github.run_attempt }},iwannadocontainerstuff/kinoservice_db:latest
